services:
  statistics-service:
    build: .
    image: statistics-service:latest
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/asset_spy_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: asset_spy_products_service_db
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      - postgres
    networks:
      - asset-spy-network
    restart: unless-stopped

networks:
  asset-spy-network:
    external: true
